Develop
Maichonok/Givenchy-SCSS pull request #8
Opened 2022-04-23 14:08 UTC by Maichonok

2022-04-25 15:08 UTC, vgschevchenko requested changes
Хорошая работа, но еще осталось над чем потрудиться.

Работа оставила приятное впечатление. 

Остались некоторые моменты, которые лучше всего исправить, чтобы можно было спокойно добавить работу в портфолио. 

	
## Критерии

1. Соответствие макету
    - [x] <!--10.0--> 1.1 Все элементы из макета сверстаны
    - [ ] <!--4.0--> 1.2 Шрифты, размер, цвет и начертания текста соответствуют макету
    - [ ] <!--4.0--> 1.3 Ширина элементов и отступы отличаются от макета не более, чем на `30px` на десктопной версии и на `10px` на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета
    - [x] <!--2.0--> 1.4 Все блоки соответствуют макету в последних версиях Firefox, Google Chrome или Yandex Browser
2. Адаптив
    - [x] <!--4.0--> 2.1 Отсутствует горизонтальный скролл на всех размерах экрана 320px и более
    - [ ] <!--1.0--> 2.2 Установленная максимальная ширина контента соответствует макету
    - [x] <!--4.0--> 2.3 Верстка не ломается между брейкпоинтами
    - [x] <!--1.0--> 2.4 Брейкпоинты сгруппированы. Если два брейкпоинта имеют небольшую пиксельную разницу в медиа-правиле они объединены в один
    - [x] <!--4.0--> 2.5 Текст не выпадает из блоков на всех размерах экрана 320px и более 
    - [x] <!--3.0--> 2.6 Изображения не искажаются и выглядят как в макете на всех размерах экрана
    - [x] <!--1.0--> 2.7 Одинаковые свойства в разных медиа-правилах не дублируются
3. Верстка
    - [ ] <!--4.0--> 3.1 Нет ошибок валидации [https://validator.w3.org/nu/](https://validator.w3.org/nu/) (Erorrs)
    - [x] <!--3.0--> 3.2 Используются `<main>`, `<section>`, `<header>`, `<footer>`, `<ul>`, `<nav>`, `<h1-h6>` и `<p>` там, где это необходимо
    - [x] <!--2.0--> 3.3 Не используются элементы `<b>`, `<br>`, `<i>`
    - [ ] <!--1.0--> 3.4 Отсутствуют лишние `div` обертки 
    - [x] <!--3.0--> 3.5 Контентные картинки вставлены через `<img>`, и в них присутствует `alt` с описанием, которое соответствует языку страницы
    - [x] <!--2.0--> 3.6 На странице есть заголовок первого уровня
    - [x] <!--2.0--> 3.7 Заголовки соответствуют иерархии страницы
    - [x] <!--1.0--> 3.8 Корректно задан `viewport`, прописаны `title` и `lang`.
4.  CSS
    - [x] <!--2.0--> 4.1 Не используется `!important`
    - [x] <!--2.0--> 4.2 Абсолютное позиционирование не используется без непосредственной необходимости
    - [x] <!--4.0--> 4.3 Использование `height` и `max-height` не приводит к выпадению текста или блоков при переполнении
    - [ ] <!--2.0--> 4.4 Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность
    - [x] <!--1.0--> 4.5 Для каждого шрифта указаны альтернативные варианты из системных шрифтов и тип шрифта
5. Применение БЭМ
    - [x] <!--4.0--> 5.1 Нет нарушения методологии БЭМ: нет элементов без родительского блока, нет элементов элементов, модификаторы не используются без указания того, что они модифицируют
    - [ ] <!--2.0--> 5.2 Не используются селекторы по тегу
    - [x] <!--3.0--> 5.3 Для одинаковых блоков в макете переиспользуется стили одного БЭМ-блока
    - [x] <!--1.0--> 5.4 Числа в названиях классов не используются, за исключением классов для элементов, указанных в руководстве по стилю (Style Guide)
    - [x] <!--1.0--> 5.5 Модификатор не отражает позицию элемента в разметке (`paragraph_first`)
    - [x] <!--1.0--> 5.6 Модификаторы не содержат дубли стилей модифицируемого элемента или блока, только изменяющиеся свойства
    - [x] <!--2.0--> 5.7 Файловая структура построена по БЭМ Nested или БЭМ Flat
- [x] <!--10.0--> 6. Функциональность на JS работает корректно (слайдеры, бургерное меню или другие требования согласно заданию на проект)
7. Структура проекта и оформление кода
    - [x] <!--2.0--> 7.1 Соблюдена единообразная файловая структура проекта, например, изображения в папке images, шрифты в папке fonts, стили в папке blocks, скрипты в папке scripts, а не разбросаны в разных папках и не хранятся в корне проекта
    - [x] <!--1.0--> 7.2 Код в проекте отформатирован единообразно
    - [x] <!--1.0--> 7.3 Нет нарушений иерархии отступов в разметке, стилях и файлах скриптов
8. Использование SCSS
	- [x] <!--2.0--> 8.1 Файлы стилей имеют расширение SCSS, подключаемый к странице CSS файл получен генерацией из SCSS файлов 
	- [x] <!--2.0--> 8.2 Повторяющеся значения вынесены в переменные, например, используемые цвета, шрифты, размеры экрана для медиазапросов
	- [ ] <!--1.0--> 8.3 Корректно используются миксины, миксины не состоят из одного CSS свойства

## Доп. комментарии:

## Количество баллов: 81

##

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
* Проверить код валидатором. Присутствуют критические ошибки(Error) валидации. Исправьте все найденные ошибки. 
	* `html`- https://validator.w3.org/#validate_by_input

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
>  <head>
* Ошибки/Ошибка в консоли на пути файлов или импортов.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +<body class="page">
Необходимо указать максимальную ширину, чтобы блоки или страница не расширялась до бесконечности и блоки не размазывались по всему экрану. Это актуально для больших разрешений.  Значение максимальной ширины должно соответствовать макету для самого большого разрешения в фигме.
https://developer.mozilla.org/ru/docs/Web/CSS/max-width

#### Не забудьте отцентровать данный блок при помощи `margin: 0 auto`.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +    <section class="about" id="about">
Нужно сравнить с макетом размеры отступов и расположение элементов. 
https://skr.sh/sDdjMP5d9et

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +        <p class="about__text">
Некорректно указан отступ сверху. 
https://skr.sh/sDdH0GvyXDn

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +      <article class="about__article">
Некорректно указан размер или отступ. 
https://skr.sh/sDdAOLiufbg

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +    <section class="looks" aria-label="Gallery" id="looks">
Блок растягивается на все 100% ширины окна. 
Нужно указать корректный размер всей странице или блоку. 
https://skr.sh/sDdeL63B9vX

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +          <input type="text" class="footer__input" required="" placeholder="Enter your email here">
Если ввести что-нибудь в полне, то цвет текста не позволяет увидеть, что было введено .
https://skr.sh/sDdPtPVfLly

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +&__input {
По умолчанию рамка должна быть белой.
При наведении идет инверсия цветов. 
https://skr.sh/sDdLsPpNyh7

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/header/_header.scss
> +  &__burger {
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/header/_header.scss
> +  &__button {
Можно лучше: 
Для плавных переходов на интерактивных элементах, можно использовать свойство `transition`.
Обычно такие вещи радуют глаз и делают взаимодействие приятным. 
Обратите внимание ниже в примере, где и как применяются данное свойство.
https://webref.ru/css/transition

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +        <img class="about__img about__img_size_m" src="images/about_woman_sits.png" alt="a woman is sitting and near bag">
Вомзожно указаны некорректные размеры или отступ. 
https://skr.sh/sDdmrjOHFtS

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +      <article class="about__article">
Вомзожно указаны некорректные размеры или отступ. 

https://skr.sh/sDdjtpxPP3r

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +    </section>
Возможно указан некорректный отступ снизу. 
https://skr.sh/sDdjgcI6LVp

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +}
Текст на мобильных нужно расположить по центру. 
https://skr.sh/sDdb5YWElJR

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/header/_header.scss
> +  &__menu {
Можно лучше: 
Попрбовать сделать плавное появление данного меню. 
https://skr.sh/sDdCwoSsgmE

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/header/_header.scss
> +  &__menu-link {
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/header/_header.scss
> +  &__close-btn {
Все интерактивные элементы должны реагировать на наведение мышью.
Должен быть  эффект наведения `:hover`.

#### Исправьте для всех ссылок или интерактивных элементов на  странице.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +    <div class="header__menu-container">
Можно лучше: 

Можно сделать так, чтобы при клике за пределы меню, оно закрывалось. 
https://skr.sh/sDd6501vEpe

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +  <link rel="icon" type="image/png" href="images/favicon.png">
• Вы молодец, указали иконку для сайта `favicon`.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +    </div>
Данный `DIV` это лишняя обертка.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +        <nav>
Элементу/блоку необходимо задать корректный класс. 
Название блока или элемента должно быть обоснованным.
Из названия должно быть понятно, что он из себя представляет и как будет дальше использоваться.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +      <button class="header__button">Subscribe to collection’s news</button>
Необходимо указать тип для ВСЕХ КНОПОК в коде. 
Если это обычная кнопка, то тогда тип `button`. 
Это полезно для доступности в будущем при разработки, а также и для сео. 
По внешнему виду кнопки разного типа никак не различаются, но у каждой такой кнопки свои функции. https://webref.ru/html/button/type

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +<body>
Это лишний тег `body`.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +      <article class="about__article">
Можно лучше: 

Отличный тег для выделения контентной информации, которая в будущем может быть переиспользована в других частях или местах страницы. 

Однако в данном случае тег `article` не лучшее решение.
Он больше подходит для переиспользуемых участков кода, таких как блоки.
В данном же случае вы используете его для элемента блока, который не может использоваться самостоятельно вне своего блока.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +      <ul class="looks__list">
• Отличное решение воспользоваться списком для перечисляемых элементов.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +        </nav>
• Не забыли выделить навигацию при помощи `nav`.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +    <div class="footer__container">
Это лишняя обертка - ее нужно удалить.

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +      <form action="#" class="footer__form">
Для формы необходимо указать уникальное имя(атрибут) `name`.
Данный атрибут задает форме уникальность для ее поиска в dom дереве и  для последующей работы с введенными в нее данными и манипуляциями при помощи javaScript и т.д
https://webref.ru/html/form/name

2022-04-25 15:08 UTC, vgschevchenko commented on index.html
> +          <input type="text" class="footer__input" required="" placeholder="Enter your email here">
Для полей не хватает атрибута `name`,  он необходим для последующей работы с формой и введенными данными, а также задает уникальность данному полю ввода.
https://webref.ru/html/input/name

2022-04-25 15:08 UTC, vgschevchenko commented on scss/index.scss
> +@import url('https://fonts.googleapis.com/css2?family=Prompt:wght@400;500&display=swap');
Можно лучше: 
Если скачать и подключить локально, то грузятся быстрее.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/mixins.scss
> +@mixin ul-reset {
Миксин сосотоит только из одного свойства, это не очень корректный подход.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +&__checkbox + label {
Используется селектор по тегу.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +&__checkbox + label::before {
Используется селектор по тегу.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +&__checkbox:checked + label::before {
Используется селектор по тегу.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +&__checkbox + label:hover::before {
Используется селектор по тегу.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/footer/_footer.scss
> +&__checkbox:checked + label:hover::before {
Используется селектор по тегу.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/header/_header.scss
> +    height: 48px;
Можно лучше:
Данному элементу можно не ограничивать жестко высоту. Если вдруг контента(текста) станет больше, чтобы элемент имел возможность расшириться, а иначе верстка сломается.

2022-04-25 15:08 UTC, vgschevchenko commented on scss/blocks/page/_page.scss
> +.page {
Необходимо указать максимальную ширину, чтобы блоки или страница не расширялась до бесконечности и блоки не размазывались по всему экрану. Это актуально для больших разрешений.  Значение максимальной ширины должно соответствовать макету для самого большого разрешения в фигме.
https://developer.mozilla.org/ru/docs/Web/CSS/max-width

#### Не забудьте отцентровать данный блок при помощи `margin: 0 auto`.

2022-04-27 11:44 UTC, Maichonok commented on index.html
> +      <article class="about__article">
> Некорректно указан размер или отступ. https://skr.sh/sDdAOLiufbg
=====
согласно макету - 20px слева и справа, https://drive.google.com/file/d/1yRvIV8DEVzBMAOfDb0b5klZZzNB61LnG/view?usp=sharing
блоку  content присвоены эти свойства

2022-04-28 09:02 UTC, closed without merging

2022-05-04 10:13 UTC, vgschevchenko commented on index.html
> +      <article class="about__article">
Да, но если наложить макет поверх верстки, то тогда не совпадает.